server:
  port: 8090
spring:
  application:
    name: resource-config-server
  profiles:
    default: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ramir0/resource-configurations
          clone-on-start: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVER_HOSTNAME}:8761/eureka/
